-- MySQL Script generated by MySQL Workbench
-- 08/14/15 19:24:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bfkltd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bfkltd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bfkltd` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bfkltd` ;

-- -----------------------------------------------------
-- Table `bfkltd`.`inci`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bfkltd`.`inci` ;

CREATE TABLE IF NOT EXISTS `bfkltd`.`inci` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_en` VARCHAR(200) NULL,
  `name_ru` VARCHAR(200) NULL,
  `name_ua` VARCHAR(200) NULL,
  `cas` VARCHAR(100) NULL,
  `einecs` VARCHAR(100) NULL,
  `smile` VARCHAR(200) NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bfkltd`.`category_structural`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bfkltd`.`category_structural` ;

CREATE TABLE IF NOT EXISTS `bfkltd`.`category_structural` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_en` VARCHAR(100) NULL,
  `name_ru` VARCHAR(100) NULL,
  `name_ua` VARCHAR(100) NULL,
  `parent_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bfkltd`.`category_application`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bfkltd`.`category_application` ;

CREATE TABLE IF NOT EXISTS `bfkltd`.`category_application` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_en` VARCHAR(100) NULL,
  `name_ru` VARCHAR(100) NULL,
  `name_ua` VARCHAR(100) NULL,
  `parent_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bfkltd`.`inci_cat_app`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bfkltd`.`inci_cat_app` ;

CREATE TABLE IF NOT EXISTS `bfkltd`.`inci_cat_app` (
  `inci_id` INT NOT NULL,
  `category_application_id` INT NOT NULL,
  PRIMARY KEY (`inci_id`, `category_application_id`),
  INDEX `fk_inci_has_category_application_category_application1_idx` (`category_application_id` ASC),
  INDEX `fk_inci_has_category_application_inci_idx` (`inci_id` ASC),
  CONSTRAINT `fk_inci_has_category_application_inci`
    FOREIGN KEY (`inci_id`)
    REFERENCES `bfkltd`.`inci` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inci_has_category_application_category_application1`
    FOREIGN KEY (`category_application_id`)
    REFERENCES `bfkltd`.`category_application` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bfkltd`.`inci_cat_struc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bfkltd`.`inci_cat_struc` ;

CREATE TABLE IF NOT EXISTS `bfkltd`.`inci_cat_struc` (
  `inci_id` INT NOT NULL,
  `category_structural_id` INT NOT NULL,
  PRIMARY KEY (`inci_id`, `category_structural_id`),
  INDEX `fk_inci_has_category_structural_category_structural1_idx` (`category_structural_id` ASC),
  INDEX `fk_inci_has_category_structural_inci1_idx` (`inci_id` ASC),
  CONSTRAINT `fk_inci_has_category_structural_inci1`
    FOREIGN KEY (`inci_id`)
    REFERENCES `bfkltd`.`inci` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inci_has_category_structural_category_structural1`
    FOREIGN KEY (`category_structural_id`)
    REFERENCES `bfkltd`.`category_structural` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bfkltd`.`property`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bfkltd`.`property` ;

CREATE TABLE IF NOT EXISTS `bfkltd`.`property` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_en` VARCHAR(100) NULL,
  `name_ru` VARCHAR(100) NULL,
  `name_ua` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bfkltd`.`property_unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bfkltd`.`property_unit` ;

CREATE TABLE IF NOT EXISTS `bfkltd`.`property_unit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `property_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_property_unit_property1_idx` (`property_id` ASC),
  CONSTRAINT `fk_property_unit_property1`
    FOREIGN KEY (`property_id`)
    REFERENCES `bfkltd`.`property` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bfkltd`.`inci_property`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bfkltd`.`inci_property` ;

CREATE TABLE IF NOT EXISTS `bfkltd`.`inci_property` (
  `inci_id` INT NOT NULL,
  `property_id` INT NOT NULL,
  `property_value` VARCHAR(50) NULL,
  `property_unit_id` INT NULL,
  PRIMARY KEY (`inci_id`, `property_id`),
  INDEX `fk_inci_has_property_property1_idx` (`property_id` ASC),
  INDEX `fk_inci_has_property_inci1_idx` (`inci_id` ASC),
  INDEX `fk_inci_property_property_unit1_idx` (`property_unit_id` ASC),
  CONSTRAINT `fk_inci_has_property_inci1`
    FOREIGN KEY (`inci_id`)
    REFERENCES `bfkltd`.`inci` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inci_has_property_property1`
    FOREIGN KEY (`property_id`)
    REFERENCES `bfkltd`.`property` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inci_property_property_unit1`
    FOREIGN KEY (`property_unit_id`)
    REFERENCES `bfkltd`.`property_unit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
